// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHsKM0yN-txbYoFI8LBSD6mDDUfrWO9gw',
    appId: '1:1003371972956:web:170fc0fa8c668f3d111999',
    messagingSenderId: '1003371972956',
    projectId: 'tstore-dbcf2',
    authDomain: 'tstore-dbcf2.firebaseapp.com',
    storageBucket: 'tstore-dbcf2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxtRRZUDqBibEB51zaHANIjGN81jbdH_k',
    appId: '1:1003371972956:android:a01d6e41679e27c7111999',
    messagingSenderId: '1003371972956',
    projectId: 'tstore-dbcf2',
    storageBucket: 'tstore-dbcf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNalJmbvrhH_5rz5c8qQPoZl2Ovghy19c',
    appId: '1:1003371972956:ios:5d2fb49d3e37f0f3111999',
    messagingSenderId: '1003371972956',
    projectId: 'tstore-dbcf2',
    storageBucket: 'tstore-dbcf2.appspot.com',
    androidClientId: '1003371972956-t13idimm3l090pkc06fqe97uka0h1249.apps.googleusercontent.com',
    iosClientId: '1003371972956-9j6vlqhnlisptma2480t6en5a520ak3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
